// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcsbqrlzycrkobhzqkyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdjc2Jxcmx6eWNya29iaHpxa3lnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NjkyNzQsImV4cCI6MjA3MDI0NTI3NH0.IVsICWZg4PJVHqwpDxUm_Pxk1enotdz4JOabHb0wzVI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});